project:
  type: website

website:
  title: "samantha-manuel.github.io-blog"
  navbar:
    right:
      - href: blogindex.qmd
        text: Blog
      - href: blogabout.qmd
        text: About
      - icon: github
        href: https://github.com/Samantha-Manuel/samantha-manuel.github.io
      - icon: twitter
        href: https://twitter.com/sami_an_manuel
format:
  html:
    theme: lux
    css: styles.css

editor: visual

